name: "Lint & Test"
run-name: Lint & Test of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.13
    with:
      worker: true
      confdir: "/app/samvera/hyrax-webapp/solr/conf"
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.13
    with:
      worker: true
      confdir: "/app/samvera/hyrax-webapp/solr/conf"